---
- hosts: localhost
  remote_user: root
  
  tasks:
   - name : update system
     apt : update_cache=yes    
  
   - name : install m4
     apt : name=m4 state=present

   - name : install build-essential
     apt : name=build-essential state=present 

   - name : install gcc
     apt : name=gcc state=present

   - name : install gfortran
     apt : name=gfortran state=present

   - name : install libssl-dev
     apt : name=libssl-dev state=present

   - name : install python-software-properties
     apt : name=python-software-properties state=present
   
   - name : add sage ppa repo
     apt_repository: repo='ppa:aims/sagemath'

   - name : update system
     apt : update_cache=yes
 
   - name : install dvipng
     apt : name=dvipng state=present

   - name : install sage binary
     apt : name=sagemath-upstream-binary state=present

   - name : create sage directory
     shell : mkdir -p ~/.sage/sage_notebook.sagenb/

   - name : copy users.pickle
     shell : cp -r users.pickle ~/.sage/sage_notebook.sagenb/ 

   - name : invoke create_sagenb script
     command: /usr/bin/screen -d -m sudo /root/databases-and-datamining-iiith/python-scripts/create_sagenb -i -y

   - name : invoke start_sage script
     command: /usr/bin/screen -d -m sudo /root/databases-and-datamining-iiith/python-scripts/start_sage -i -y
   
   - name : run makefile
     command : make -C ../src     

   - name : rename index.html
     command : rm -rf index.html

   - name : copy index.html file
     shell : cp -r index.html /var/www/

   - name : configure apache
     shell : cat apacheconfig >> /etc/apache2/sites-enabled/000-default

   - name : enable a2enmod proxy module 
     shell : a2enmod proxy
   
   - name : enable a2enmod proxy_http module
     shell : a2enmod proxy_http

   - name : restart apache server
     service : name=apache2 state=started
